apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{gitops.name}}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{gitops.name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{gitops.name}}
subjects:
- kind: ServiceAccount
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{gitops.name}}-server-conf
  labels:
    name: {{gitops.name}}-server-conf
  namespace: {{gitops.namespace}}
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      external_labels:
        origin_prometheus: {{gitops.config.store}}
    rule_files:
      - /etc/prometheus/prometheus.rules
    remote_write:
    - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
      basic_auth:
        username: 261866
        password_file: /etc/prometheus/secrets/password
    scrape_configs:
      - job_name: 'webv-heartbeat'
        static_configs:
          - targets: [ 'webv-heartbeat.webv.svc.cluster.local:8080' ]
        metric_relabel_configs:
        - source_labels: [ __name__ ]
          regex: "WebVDuration_bucket|WebVDuration_sum|WebVSummary_sum"
          action: drop
      - job_name: 'webv-aioa'
        static_configs:
          - targets: [ 'webv-aioa.webv.svc.cluster.local:8080' ]
        metric_relabel_configs:
        - source_labels: [ __name__ ]
          regex: "WebVDuration_bucket|WebVDuration_sum|WebVSummary_sum"
          action: drop

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}-deployment
  namespace: {{gitops.namespace}}
  labels:
    app: {{gitops.name}}-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.name}}-server
  template:
    metadata:
      labels:
        app: {{gitops.name}}-server
    spec:
      containers:
        - name: {{gitops.name}}
          image: {{gitops.imageName}}
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 250m
              memory: 250M
            limits:
              cpu: 500M
              memory: 500M
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
            - name: prometheus-secret-volume
              mountPath: /etc/prometheus/secrets
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf

        - name: prometheus-secret-volume
          secret:
            secretName: prom-secrets
  
        - name: prometheus-storage-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}-service
  namespace: {{gitops.namespace}}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: {{gitops.name}}-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000
